![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [1]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print("POP")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [3]:
# TESTANDO
S = Stack()

In [5]:
type (S)

__main__.Stack

In [7]:
S.print_stack()

[]


In [9]:
S.push(1)

PUSH 1


In [11]:
S.push(2)

PUSH 2


In [13]:
S.push(3)

PUSH 3


In [15]:
S.print_stack()

[1, 2, 3]


In [17]:
S.pop()

POP


3

In [19]:
S.pop()

POP


2

In [21]:
S.print_stack()

[1]


In [23]:
S.push(7)

PUSH 7


In [25]:
S.push(8)

PUSH 8


In [27]:
S.push(9)

PUSH 9


In [29]:
S.print_stack()

[1, 7, 8, 9]


In [31]:
print(S.is_empty())

False


### Segunda Implementação

In [33]:
import numpy as np

In [35]:
class Pilha:
    def __init__(self, capacidade):      #init é um construtor
        self.__capacidade = capacidade      #__ forma que fazemos para dizer que o atributo é privado, capacidade quantidade de elementos
        self.__topo = -1       # -1 representa uma posição fantasma, referencia que não tem nada
        self.__valores = np.zeros(self.__capacidade, dtype=int)      # np.zeros cria um vetor, ou localização de zeros para serem preenchidas

    def __pilha_cheia(self):     #__pilha_cheia - método privado, só pode ser acessado de dentro da classe
        if self.__topo == self.__capacidade - 1:      # se estiver cheio, será False, se não True
            return True
        else:    
            return False
    
    def __pilha_vazia(self):     
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):      #recebendo o valor a ser empilhado
        if self.__pilha_cheia():   # se a pilha estiver cheia, não consigo mais empilhar
            print('A pilha está cheia')
        else:
            self.__topo += 1 #adiciona o 1 na primeira posição que é zero
            self.__valores[self.__topo] = valor
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')    # se estiver vazia não posso desempilhar
           #return -1
        else:
            #aux = self.__valores[self.__topo]
            self.__valores[self.__topo] = 0
            self.__topo -= 1      #coloco o zero no topo da pilha
            #return aux      #para armazenar o valor e não perder
            
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]      #se for -1 está vazio
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):      #mostra os valores
        print(self.__valores)

In [37]:
pilha = Pilha(5)    #pilha = variável  - Pilha = classe

In [39]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [69]:
pilha.ver_topo()

1

In [71]:
pilha.empilhar(1)
pilha.ver_topo()

1

In [73]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

A pilha está cheia
A pilha está cheia


In [75]:
pilha.imprime_pilha()

[1 1 1 1 2]


In [77]:
pilha.empilhar(6)

A pilha está cheia


In [79]:
pilha.ver_topo()

2

In [81]:
pilha.desempilhar()

In [83]:
pilha.ver_topo()

1

In [85]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

In [87]:
pilha.ver_topo()

1

In [89]:
pilha.imprime_pilha()

[1 0 0 0 0]


In [91]:
pilha.desempilhar()

In [93]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [95]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
## Exercício

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [113]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [120]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

Entre com um número inteiro:  145


PUSH 1
PUSH 0
PUSH 0
PUSH 0
PUSH 1
PUSH 0
PUSH 0
PUSH 1
POP
POP
POP
POP
POP
POP
POP
POP
O valor 145 em binário é: 10010001


### Fim Teoria Aula 6

In [ ]:
Criando um Validador de () {} e []

In [160]:
class Stack:  # Criação de uma classe chamada Stack (Pilha)
    def __init__(self):  # Método especial de inicialização (construtor)
        self.lista = []  # Inicializa um atributo da classe, chamado items, que é uma lista vazia. Ele será usado para armazenar os elementos da pilha.

    def push(self, lista):  # Método para adicionar um item à pilha
        self.lista.append(lista)  # Adiciona o item no final da lista, que é a forma de empilhar (push) na pilha.

    def pop(self):  # Método para remover o item do topo da pilha
        if not self.is_empty():  # Verifica se a pilha não está vazia antes de tentar remover um item
            return self.lista.pop()  # Remove e retorna o último item da lista (topo da pilha)
        return None  # Caso a pilha esteja vazia, retorna None.

    def is_empty(self):  # Método que verifica se a pilha está vazia
        return len(self.lista) == 0  # Retorna True se o comprimento da lista for 0 (indicando que está vazia), caso contrário retorna False.

def validar_sequencia(s):  # Função que valida se a sequência de parênteses, colchetes e chaves está correta
    pilha = Stack()  # Cria uma instância da classe Stack para armazenar os caracteres.
    pares = {')': '(', ']': '[', '}': '{'}  # Dicionário que mapeia os caracteres de fechamento para seus respectivos caracteres de abertura.

    for char in s:  # Itera sobre cada caractere na string de entrada
        if char in pares.values():  # Se o caractere for um de abertura ('(', '[', '{')
            pilha.push(char)  # Empilha o caractere na pilha.
        elif char in pares.keys():  # Se o caractere for um de fechamento (')', ']', '}')
            if pilha.is_empty() or pilha.pop() != pares[char]:  # Se a pilha estiver vazia ou o topo da pilha não corresponder ao par correto
                return False  # Retorna False, indicando que a sequência é inválida

    return pilha.is_empty()  # Se a pilha estiver vazia no final, retorna True (sequência válida). Caso contrário, retorna False.

# Entrada do usuário
sequencia = input("Digite a sequência de parênteses, colchetes e chaves para validar: ")  # Solicita que o usuário insira uma sequência de caracteres
if validar_sequencia(sequencia):  # Chama a função de validação passando a sequência do usuário
    print("True!")  # Se a sequência for válida, imprime "True!"
else:
    print("False!")  # Caso contrário, imprime "False!"



Digite a sequência de parênteses, colchetes e chaves para validar:  {[(0)]}


True!


In [162]:
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        return None

    def is_empty(self):
        return len(self.items) == 0

def validar_sequencia(s):
    pilha = Stack()
    pares = {')': '(', ']': '[', '}': '{'}
    caracteres_validos = "({[]})"  # Define os caracteres permitidos

    for char in s:
        if char not in caracteres_validos:  # Se encontrar um caractere inválido
            print("Não é (), [] ou {}, insira apenas uma das três.")
            return False
        if char in pares.values():
            pilha.push(char)
        elif char in pares.keys():
            if pilha.is_empty() or pilha.pop() != pares[char]:
                return False

    return pilha.is_empty()

# Entrada do usuário
sequencia = input("Digite a sequência de parênteses, colchetes e chaves para validar: ")

if validar_sequencia(sequencia):
    print("True!")
else:
    print("False!")


Digite a sequência de parênteses, colchetes e chaves para validar:  {[(0)]}


Não é (), [] ou {}, insira apenas uma das três.
False!


Implemente um históriao de ações para defazer e refazer operações em um editor de texto básico

In [ ]:
class EditorTexto:
    def __init__(self):
        self.texto = []  # Pilha principal para armazenar as palavras
        self.desfeitos = []  # Pilha auxiliar para armazenar palavras desfeitas

    def escrever(self, palavra):
        """Adiciona uma palavra ao texto e limpa a pilha de desfeitos."""
        self.texto.append(palavra)
        self.desfeitos.clear()  # Sempre que o usuário digita algo novo, a pilha de refazer é limpa

    def undo(self):
        """Remove a última palavra e a armazena para possível refazer."""
        if self.texto:
            self.desfeitos.append(self.texto.pop())  # Move a última palavra para a pilha de desfeitos
        else:
            print("Nada para desfazer!")

    def redo(self):
        """Restaura a última palavra removida, se houver."""
        if self.desfeitos:
            self.texto.append(self.desfeitos.pop())  # Recupera a última palavra removida
        else:
            print("Nada para refazer!")

    def exibir_texto(self):
        """Mostra o texto atual formatado."""
        print("Texto atual:", " ".join(self.texto))

# Criando o editor de texto
editor = EditorTexto()

print("Digite palavras para escrever. Use 'UNDO' para remover a última palavra e 'REDO' para restaurá-la.")
print("Digite 'SAIR' para encerrar o programa.\n")

while True:
    entrada = input("Digite uma palavra: ").strip()

    if entrada.upper() == "SAIR":
        break
    elif entrada.upper() == "UNDO":
        editor.undo()
    elif entrada.upper() == "REDO":
        editor.redo()
    else:
        editor.escrever(entrada)

    editor.exibir_texto()


Digite palavras para escrever. Use 'UNDO' para remover a última palavra e 'REDO' para restaurá-la.
Digite 'SAIR' para encerrar o programa.



Digite uma palavra:  Hello


Texto atual: Hello


Digite uma palavra:  Word


Texto atual: Hello Word


Digite uma palavra:  undo


Texto atual: Hello


Digite uma palavra:  redo


Texto atual: Hello Word
